server:
  servlet:
    context-path: /helloSpb

#spb内置logback，配置有两种方式，使用时二者选其一即可：
#方式一：logback的配置可以在application.yml里面进行简单滴配置，如下：
#logging:
#  file:
#    name: /Users/zhangzhiwang/Desktop/spb.log #设置输出的日志文件
#  level:  #设置日志级别，是一个Map：key为包名，value为日志级别
#    org.springframework: info
#    com.asiainfo.controller: debug
#    com.asiainfo.service: debug
#方式二：ogback的配置也可以单独地放在一个配置文件里面，这个配置文件的名字是logback.xml，且该文件无需被application.yml引入或者在代码中引入，单独存在即可。
#因为spb内置logback，所以会默认在项目的classpath路径下按顺序查找名为logback-test.xml、logback.groovy、logback.xml的文件，如果上述文件均未找到，则使用默认配置（debug级别）将日志输出到控制台

spring:
  profiles:
    active:
    - prod  #激活对应的配置文件，命名规则为application-${spring.profiles.active}.yml或者properties，注意application后面必须是“-”而不是“_”
  webflux:
    static-path-pattern: /aaa/bbb/ccc/**  #静态资源路径模式匹配，符合该模式的走静态资源访问，如果配置成“/**”则表示所有路径都要先经过静态资源访问，如果找不到静态资源再去找动态资源映射到controller
  resources:
    static-locations: #自定义静态资源路径，默认的为classpath:/static和/src/main/webapp，注意如果配置了自定义的静态资源路径那么默认的classpath:/static已经不生效了，如果仍然需要访问classpath:/static里面的资源必须显式地进行配置
    - classpath:/zzw
    - classpath:/xjk
    - classpath:/static #虽然是默认的但如果配置了其它自定义的静态资源路径，该路径也必须显式地配置
    - classpath:/META-INF/resources #第三方jar包的静态资源路径

user: 
  userName: 张
  age: 18
  