server:
  port: 8091
  
spring:
  application:
    name: GuPaoEdu-SpringCloudNetflix-Consumer-User-1
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8987/eureka,http://localhost:8988/eureka,http://localhost:8989/eureka #配置集群的所有节点以防单点故障
    register-with-eureka: true
    fetch-registry: true  #本工程最为消费者必须从eureka获取注册信息