server:
  port: 8092
  
dubbo:
  application:
    name: provider-3
  registries:
    beijing:  #相当于配置文件：<dubbo:registry id="beijing" address="nacos://127.0.0.1:8848" />
      address: nacos://127.0.0.1:8848
    shanghai: #相当于配置文件：<dubbo:registry id="shanghai" address="zookeeper://127.0.0.1:2181" />
      address: zookeeper://127.0.0.1:2181
#  protocol:
#    name: dubbo
  protocols:  #dubbo配置多协议
    protocal_1:  #相当于配置文件：<dubbo:protocol id="protocal_1" name="dubbo" port="-1" />
      name: dubbo
      port: 20882 #不指定协议端口让系统自动生成
    protocal_2:  #相当于配置文件：<dubbo:protocol id="protocal_2" name="rest" port="-1" />
      name: rest  #如果使用rest协议则需要做三方面配置：1、引入依赖：resteasy-jaxrs、resteasy-client、jetty-server和jetty-servlet 2、配置文件在配置rest协议时要加上web容器的配置，即server属性 3、要在接口上加上rest的路径注解@Path
      port: 82
      server: jetty  #rest协议需要web容器的支持，这里容器选择jetty