server:
  port: 8090
  
dubbo:
  application:
    name: provider-1
  registries:
    beijing:
      address: nacos://127.0.0.1:8848
    shanghai:
      address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo