server:
  port: 8081
  
spring:
  application:
    name: GuPaoEdu-SpringCloudNetflix-Provider-Product-1  #本工程是产品微服务的生产者
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8989/eureka
    register-with-eureka: true  #本工程作为服务的提供者必须系那个eureka注册自己
    fetch-registry: false #有无本工程不需要最为消费者来调用服务作为不需要从eureka获取注册信息