server:
  port: 8081
  
dubbo:
  application:
    name: consumer-1
#  registry:
#    address: nacos://127.0.0.1:8848
  registries:
    beijing:
      address: nacos://127.0.0.1:8848
#      weight: 100 #权重。weight、zone和preferred都是干预dubbo对多注册中心的负载
#      zone: beijing  #区域优先
#      preferred: true #优先选择
    shanghai:
      address: zookeeper://127.0.0.1:2181
#      weight: 10