server:
  port: 8989
  
spring:
  application:
    name: GuPaoEdu-SpringCloudNetflix-Eureka-1
    
eureka:
  client:
    register-with-eureka: false #是否将本工程注册到eureka服务，因为本工程就是eureka服务不需要注册自己
    fetch-registry: false #是否从eureka服务拉取注册信息，因为本工程就是eureka服务不需要拉取任何注册信息