server:
  port: 8987
  
spring:
  application:
    name: GuPaoEdu-SpringCloudNetflix-Eureka-1
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8988/eureka,http://localhost:8989/eureka #eureka集群要互相注册。注意：每一个节点要配置上其它所有节点的地址，而不是配置其它节点的任意一个
    register-with-eureka: false #是否将本工程注册到eureka服务，因为本工程就是eureka服务不需要注册自己
    fetch-registry: false #是否从eureka服务拉取注册信息，因为本工程就是eureka服务不需要拉取任何注册信息
  server:
    enable-self-preservation: false #eureka的自我保护机制，默认是开启的。当eureka服务端没收到客户端的心跳达到一定阈值（默认情况下15分钟内超过85%的客户端节点都没有正常的心跳）的时候，会出发自我保护机制。没有收到心跳可能是由于eureka的server端和client端的网络抖动或者网络有问题，但实际上服务本身是没有问题的，这个时候如果强制服务下线会导致服务消费者调用失败，导致系统的不可用。
                                    #为了提高系统的高可用性，eureka开启自我保护模式，即将临时不可用的服务缓存起来，这样服务消费者依然能够从eureka服务端获取生产者的信息从而调用服务，当恢复心跳时退出自我保护模式